### ISSUE TITLE
你好 请问一下运行此项目的时候出现Error: While importing 'bbs', an ImportError was raised. 这个怎么解决呢

### ISSUE THREAD

**Issue by lone0x0** [weijiang1994/bbs-admin-backend#21]
![截屏2022-02-22 14 40 45](https://user-images.githubusercontent.com/78702504/155076851-7848062a-8cc0-4c95-bb6b-445af627a4d2.png)

**Comment by weijiang1994** [comment]
重新`fetch`一下代码，有几个包忘记加到requirements.txt中去了

**Comment by weijiang1994** [comment]
![image](https://user-images.githubusercontent.com/53400477/155078204-684a3c6f-13c9-47a4-9e4a-06f96b674b3a.png)
zsh同款主题啊~ :smile_cat:

**Comment by lone0x0** [comment]
> ![image](https://user-images.githubusercontent.com/53400477/155078204-684a3c6f-13c9-47a4-9e4a-06f96b674b3a.png) zsh同款主题啊~ 😸

可以可以 哪请问下是哪几个包忘记加了

**Comment by weijiang1994** [comment]
> > ![image](https://user-images.githubusercontent.com/53400477/155078204-684a3c6f-13c9-47a4-9e4a-06f96b674b3a.png) zsh同款主题啊~ smile_cat
> 
> 可以可以 哪请问下是哪几个包忘记加了

https://github.com/weijiang1994/bbs-admin-backend/commit/0ec5e8f53ada82ec8b25501b1257645a5d9ebec7 看这个提交记录就知道了~

**Comment by lone0x0** [comment]
老哥 运行了这个项目加vue项目 但是还是登不进去
![截屏2022-02-22 15 04 57](https://user-images.githubusercontent.com/78702504/155079982-e0d0164f-db23-46a6-bf77-a45449a7baa0.png)

![截屏2022-02-22 15 04 20](https://user-images.githubusercontent.com/78702504/155080054-67b45532-e89d-42b1-87c4-6f1ffd971589.png)
![截屏2022-02-22 15 08 53](https://user-images.githubusercontent.com/78702504/155080546-e4d10bcf-90b0-4253-b447-fd60d4916baf.png)

**Comment by weijiang1994** [comment]
vue配置文件后端默认用的8008端口，用这个命令启动后端`flask run --port 8008`

**Comment by weijiang1994** [comment]
![image](https://user-images.githubusercontent.com/53400477/155082630-cad74bed-abaa-45b4-8257-edef80d52a03.png)

哈哈哈，我是说看你的github ID那么眼熟咯，原来你是我网站的第一个注册用户啊~ :laughing:

**Comment by lone0x0** [comment]
> ![image](https://user-images.githubusercontent.com/53400477/155082630-cad74bed-abaa-45b4-8257-edef80d52a03.png)
> 
> 哈哈哈，我是说看你的github ID那么眼熟咯，原来你是我网站的第一个注册用户啊~ 😆

是的 当时想学习一下flask 但是一直没时间学 到现在才有点时间

**Comment by weijiang1994** [comment]
> > ![image](https://user-images.githubusercontent.com/53400477/155082630-cad74bed-abaa-45b4-8257-edef80d52a03.png)
> > 哈哈哈，我是说看你的github ID那么眼熟咯，原来你是我网站的第一个注册用户啊~ laughing
> 
> 是的 当时想学习一下flask 但是一直没时间学 到现在才有点时间

嗯，能运行了吧？

**Comment by lone0x0** [comment]
> > > ![image](https://user-images.githubusercontent.com/53400477/155082630-cad74bed-abaa-45b4-8257-edef80d52a03.png)
> > > 哈哈哈，我是说看你的github ID那么眼熟咯，原来你是我网站的第一个注册用户啊~ laughing
> > 
> > 
> > 是的 当时想学习一下flask 但是一直没时间学 到现在才有点时间
> 
> 嗯，能运行了吧？

还是不行，我看了下我的配置文件 数据库账号密码是对的 然后就是登不进去
![截屏2022-02-22 15 30 23](https://user-images.githubusercontent.com/78702504/155084579-b5a7fcd5-ee60-482b-abfa-25988747251a.png)
![截屏2022-02-22 15 31 48](https://user-images.githubusercontent.com/78702504/155084626-4487cbe4-62ae-482c-b714-c7b34f1baeb6.png)
![截屏2022-02-22 15 33 29](https://user-images.githubusercontent.com/78702504/155084655-24896c5c-e1c3-4d22-a772-86486479a45f.png)
![截屏2022-02-22 15 34 29](https://user-images.githubusercontent.com/78702504/155084665-036647c9-8972-4e33-80e4-cdfa8d16246d.png)
![截屏2022-02-22 15 38 54](https://user-images.githubusercontent.com/78702504/155084795-b66e284d-69fb-4e12-b0b3-0d1b6e282df9.png)

**Comment by weijiang1994** [comment]
密码中不要带有`@`符号

**Comment by weijiang1994** [comment]
![image](https://user-images.githubusercontent.com/53400477/155085495-4e9e2fcf-6ef5-427e-8598-402fd1d4950e.png)
MySQL连接会自动从@符号开始把后面的当做你的MySQL的服务器地址的~

**Comment by lone0x0** [comment]
> ![image](https://user-images.githubusercontent.com/53400477/155085495-4e9e2fcf-6ef5-427e-8598-402fd1d4950e.png) MySQL连接会自动从@符号开始把后面的当做你的MySQL的服务器地址的~

ok 感谢老哥

**Comment by weijiang1994** [comment]
> > ![image](https://user-images.githubusercontent.com/53400477/155085495-4e9e2fcf-6ef5-427e-8598-402fd1d4950e.png) MySQL连接会自动从@符号开始把后面的当做你的MySQL的服务器地址的~
> 
> ok 感谢老哥

方便的话，帮我点个 :star: 谢谢啦~
