### ISSUE TITLE
你好老哥 今天我测试的时候 发现上传图片时 服务器错误，还有新建主题时候 id为啥是从7开始？

### ISSUE THREAD

**Issue by lone0x0** [weijiang1994/bbs-admin-backend#23]
![截屏2022-02-24 15 26 24](https://user-images.githubusercontent.com/78702504/155478076-6f391eeb-80f9-4ed6-aaf7-1f3a877cd271.png)
![截屏2022-02-24 15 26 43](https://user-images.githubusercontent.com/78702504/155478088-d64d7f34-ea56-41e9-871d-ff99238cfdc4.png)
![截屏2022-02-24 15 26 51](https://user-images.githubusercontent.com/78702504/155478090-4580bd7c-09a7-4972-958a-ec57b1df79bb.png)
![截屏2022-02-24 15 28 48](https://user-images.githubusercontent.com/78702504/155478156-be0ba798-0a79-43f8-afe2-a153e53cd3c0.png)

**Comment by weijiang1994** [comment]
错误原因是因为你没有创建保存图片的文件夹

**Comment by lone0x0** [comment]
> 错误原因是因为你没有创建保存图片的文件夹

已经创建了 然后还是没保存下来
![截屏2022-02-24 16 20 11](https://user-images.githubusercontent.com/78702504/155485680-8b75649c-02bb-44e2-9a3e-e221b632c0d0.png)

**Comment by weijiang1994** [comment]
你配置文件里面配置的`/img/`，那这个目录应该创建在你的磁盘分区的根目录，你如果想创建在项目目录下，就把你项目目录下的`img`目录的绝对路径放到配置文件里面去。

**Comment by lone0x0** [comment]
> 你配置文件里面配置的`/img/`，那这个目录应该创建在你的磁盘分区的根目录，你如果想创建在项目目录下，就把你项目目录下的`img`目录的绝对路径放到配置文件里面去。

ok 是我想错了 现在可以了
